@hostname = localhost
@port  = 8080
@name = "Laszlo"
@password = "SecretPassword"  
@email = "laszlo@example.com"

@name2 = "Laci"
@password2 = "VerySecretPassword"  
@email2 = "laci@example.com"


###
# Sign up with the first user
POST http://{{hostname}}:{{port}}/signup HTTP/1.1
content-type: application/json

{
    "name": {{name}},
    "password": {{password}},
    "email": {{email}}
}

###
# Sign up with the second user
POST http://{{hostname}}:{{port}}/signup HTTP/1.1
content-type: application/json

{
    "name": {{name2}},
    "password": {{password2}},
    "email": {{email2}}
}

###
# Login with the first user
POST http://{{hostname}}:{{port}}/login HTTP/1.1
content-type: application/json

{
    "password": {{password}},
    "email": {{email}}
}

###
# Login with the second user
POST http://{{hostname}}:{{port}}/login HTTP/1.1
content-type: application/json

{
    "password": {{password2}},
    "email": {{email2}}
}

###
# Logout
DELETE http://{{hostname}}:{{port}}/logout HTTP/1.1
